### ISSUE TITLE
源码没有提交？。。。。

### ISSUE THREAD

**Issue by martianmartian** [klover2/wechatpay-node-v3-ts#13]
老兄，这是开源吗？怎么看不到源码

**Comment by martianmartian** [comment]
啊，就只有index.js吗。。是我看错了吗

**Comment by klover2** [comment]
> 啊，就只有index.js吗。。是我看错了吗

这就是对微信v3支付封装的一些方法

**Comment by klover2** [comment]
> 啊，就只有index.js吗。。是我看错了吗

你没有看错，就是它。你难道觉得微信支付会很复杂？一个文件搞不定？？
