### ISSUE TITLE
商户分账接口调用报错

### ISSUE THREAD

**Issue by lenlee817** [klover2/wechatpay-node-v3-ts#14]
调试了native支付，还有查询关闭的接口，都调试通了，但调试分账接口时候，报错：
{"code":"PARAM_ERROR","message":"请确认待处理的消息是否为加密后的密文"}
是目前不支持分账吗？还是什么问题？

**Comment by klover2** [comment]
> 调试了native支付，还有查询关闭的接口，都调试通了，但调试分账接口时候，报错： {"code":"PARAM_ERROR","message":"请确认待处理的消息是否为加密后的密文"} 是目前不支持分账吗？还是什么问题？

你需要查看一下微信商户是否有分账的权限
