### ISSUE TITLE
企业付款

### ISSUE THREAD

**Issue by devoutDisciple** [klover2/wechatpay-node-v3-ts#15]
您好，是否可以添加企业付款到个人零钱账户的api，这个用的也挺多的

**Comment by klover2** [comment]
> 您好，是否可以添加企业付款到个人零钱账户的api，这个用的也挺多的

是有的 因为这个接口还是v2版的所以没有写到这里来，你可以参考我这个npm 包 [node-wxpay](https://www.npmjs.com/package/node-wxpay3)
