### ISSUE TITLE
APP 支付签名支付失败

### ISSUE THREAD

**Issue by LittleMonsterAK** [klover2/wechatpay-node-v3-ts#21]
APP支付的时候 签名参数应该是下面几个
应用id
时间戳
随机字符串
预支付交易会话ID

现在代码里面写的是package=sign=wxpay，文档上应该是预支付交易会话ID

**Comment by klover2** [comment]
微信文档： https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_2_4.shtml
![image](https://user-images.githubusercontent.com/49548817/174564889-372ca4e6-abdd-495b-8668-09ec11835614.png)

**Comment by klover2** [comment]
除非微信更新了，但是没有更新文档

**Comment by LittleMonsterAK** [comment]
> 除非微信更新了，但是没有更新文档

文档是没错，也没更新，是代码里面对签名字段的拼接不对，不是用data.package 而是使用data.prepayid
<img width="791" alt="image" src="https://user-images.githubusercontent.com/4099007/176584268-f17d89fe-0b93-4b46-9457-71a413aadf4b.png">
![image](https://user-images.githubusercontent.com/4099007/176584315-c18f6e3a-46be-416e-91ac-c2dde5413f2c.png)
![image](https://user-images.githubusercontent.com/4099007/176584515-af13f6d3-7980-4e60-962d-8dd2cfc49175.png)

**Comment by klover2** [comment]
> > 除非微信更新了，但是没有更新文档
> 
> 文档是没错，也没更新，是代码里面对签名字段的拼接不对，不是用data.package 而是使用data.prepayid <img alt="image" width="791" src="https://user-images.githubusercontent.com/4099007/176584268-f17d89fe-0b93-4b46-9457-71a413aadf4b.png"> ![image](https://user-images.githubusercontent.com/4099007/176584315-c18f6e3a-46be-416e-91ac-c2dde5413f2c.png) ![image](https://user-images.githubusercontent.com/4099007/176584515-af13f6d3-7980-4e60-962d-8dd2cfc49175.png)

如果可以的话你提一个pr改下这个问题，我想把你拉入到我这个开放的api维护里面来。

**Comment by LittleMonsterAK** [comment]
> > 除非微信更新了，但是没有更新文档
> 
> 文档是没错，也没更新，是代码里面对签名字段的拼接不对，不是用data.package 而是使用data.prepayid <img alt="image" width="791" src="https://user-images.githubusercontent.com/4099007/176584268-f17d89fe-0b93-4b46-9457-71a413aadf4b.png"> ![image](https://user-images.githubusercontent.com/4099007/176584315-c18f6e3a-46be-416e-91ac-c2dde5413f2c.png) ![image](https://user-images.githubusercontent.com/4099007/176584515-af13f6d3-7980-4e60-962d-8dd2cfc49175.png)



> > > 除非微信更新了，但是没有更新文档
> > 
> > 
> > 文档是没错，也没更新，是代码里面对签名字段的拼接不对，不是用data.package 而是使用data.prepayid <img alt="image" width="791" src="https://user-images.githubusercontent.com/4099007/176584268-f17d89fe-0b93-4b46-9457-71a413aadf4b.png"> ![image](https://user-images.githubusercontent.com/4099007/176584315-c18f6e3a-46be-416e-91ac-c2dde5413f2c.png) ![image](https://user-images.githubusercontent.com/4099007/176584515-af13f6d3-7980-4e60-962d-8dd2cfc49175.png)
> 
> 如果可以的话你提一个pr改下这个问题，我想把你拉入到我这个开放的api维护里面来。

OK Pr已经提了 https://github.com/klover2/wechatpay-node-v3-ts/pull/22

**Comment by klover2** [comment]
已经发布新版本wechatpay-node-v3@1.3.5

**Comment by klover2** [comment]
> > > 除非微信更新了，但是没有更新文档
> > 
> > 
> > 文档是没错，也没更新，是代码里面对签名字段的拼接不对，不是用data.package 而是使用data.prepayid <img alt="image" width="791" src="https://user-images.githubusercontent.com/4099007/176584268-f17d89fe-0b93-4b46-9457-71a413aadf4b.png"> ![image](https://user-images.githubusercontent.com/4099007/176584315-c18f6e3a-46be-416e-91ac-c2dde5413f2c.png) ![image](https://user-images.githubusercontent.com/4099007/176584515-af13f6d3-7980-4e60-962d-8dd2cfc49175.png)
> 
> > > > 除非微信更新了，但是没有更新文档
> > > 
> > > 
> > > 文档是没错，也没更新，是代码里面对签名字段的拼接不对，不是用data.package 而是使用data.prepayid <img alt="image" width="791" src="https://user-images.githubusercontent.com/4099007/176584268-f17d89fe-0b93-4b46-9457-71a413aadf4b.png"> ![image](https://user-images.githubusercontent.com/4099007/176584315-c18f6e3a-46be-416e-91ac-c2dde5413f2c.png) ![image](https://user-images.githubusercontent.com/4099007/176584515-af13f6d3-7980-4e60-962d-8dd2cfc49175.png)
> > 
> > 
> > 如果可以的话你提一个pr改下这个问题，我想把你拉入到我这个开放的api维护里面来。
> 
> OK Pr已经提了 #22

已经发布新版本
wechatpay-node-v3@1.3.5
