### ISSUE TITLE
回调解密 （支付成功通知 退款通知）的入参请详细说明一下

### ISSUE THREAD

**Issue by jkkongkong** [klover2/wechatpay-node-v3-ts#27]
回调解密 （支付成功通知 退款通知）的入参请详细说明一下，各个参数代表什么意思，如何获取，请详细说明下 ，小白不太懂，谢谢！

**Comment by klover2** [comment]
> 回调解密 （支付成功通知 退款通知）的入参请详细说明一下，各个参数代表什么意思，如何获取，请详细说明下 ，小白不太懂，谢谢！

请看 https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_2.shtml
