### ISSUE TITLE
wechatpay_node_v3_1.default is not a constructor

### ISSUE THREAD

**Issue by soul0932** [klover2/wechatpay-node-v3-ts#28]
/Users/soulmac/code/node/Nest/src/app.controller.ts:11
const pay = new Pay(
            ^
TypeError: wechatpay_node_v3_1.default is not a constructor

用在nestjs里时一使用就报这个错误，请问有人能解答一下吗

**Comment by soul0932** [comment]
已解决：https://github.com/klover2/wechatpay-node-v3-ts/issues/20

**Comment by klover2** [comment]
推荐使用npm install nest-wechatpay-node-v3
