### ISSUE TITLE
签名失败

### ISSUE THREAD

**Issue by WhatsNew3** [klover2/wechatpay-node-v3-ts#29]
你好，我在使用的时候，发现签名失败，请问这个是什么问题呢？
`const signature = pay.getSignature('POST', nonce_str, timestamp, '/v3/pay/transactions/jsapi', params)`
出现报错：
`Error: error:0909006C:PEM routines:get_name:no start line`

我是证书是使用WXCert生成的

**Comment by klover2** [comment]
> 你好，我在使用的时候，发现签名失败，请问这个是什么问题呢？ `const signature = pay.getSignature('POST', nonce_str, timestamp, '/v3/pay/transactions/jsapi', params)` 出现报错： `Error: error:0909006C:PEM routines:get_name:no start line`
> 
> 我是证书是使用WXCert生成的

你证书格式错了，参考下面看下自己的证书里面是否有

pkcs1——公钥从头开始-----BEGIN RSA PUBLIC KEY-----，私钥从头-----BEGIN RSA PRIVATE KEY-----开始
pkcs8——公钥从头开始-----BEGIN PUBLIC KEY-----，私钥从头-----BEGIN PRIVATE KEY-----开始
openssh——公钥从头开始ssh-rsa，私钥从头-----BEGIN OPENSSH PRIVATE KEY-----开始

**Comment by klover2** [comment]
> 你好，我在使用的时候，发现签名失败，请问这个是什么问题呢？ `const signature = pay.getSignature('POST', nonce_str, timestamp, '/v3/pay/transactions/jsapi', params)` 出现报错： `Error: error:0909006C:PEM routines:get_name:no start line`
> 
> 我是证书是使用WXCert生成的

可以参考文档 https://blog.csdn.net/qq_17255515/article/details/124599726
