### ISSUE TITLE
功能小建议：非通用API签名

### ISSUE THREAD

**Issue by mr-xiangxu** [klover2/wechatpay-node-v3-ts#30]
除了微信支付”接口规则“（https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay-1.shtml），
中需要API调用端进行签名（本repo实现的内容），微信支付其他API也有需要（不同规则的）签名的，
比如：
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter3_5_4.shtml

希望repo也能实现它们，方便开发者。

**Comment by klover2** [comment]
是有提供的，看下下面这个是否能够满足
 
  # 获取签名
    const signature = pay.getSignature('POST', nonce_str, timestamp, url, params); # 如果是get 请求 则不需要params 参数拼接在url上 例如 /v3/pay/transactions/id/12177525012014?mchid=1230000109

**Comment by klover2** [comment]
是有提供的 只是我给隐藏的

const str = [data.appId, data.timeStamp, data.nonceStr, data.package, ''].join('\n');
 const paySign = this.sha256WithRsa(str);
 
 但是我这边推荐你使用我封装好的方法，发起支付的参数都已经处理好了，文档 https://github.com/klover2/wechatpay-node-v3-ts/blob/master/docs/transactions_jsapi.md
