### ISSUE TITLE
商家转账到零钱出现： 确认待处理的消息是否为加密后的密文

### ISSUE THREAD

**Issue by liu5201314-cyf** [klover2/wechatpay-node-v3-ts#34]
我已经把wechatpay-node-v3更新到最新版本了，但是运行代码后会报下面的错误，大佬帮帮忙啊，呜呜呜！！！
![image](https://user-images.githubusercontent.com/60703657/193437094-71b2e352-26aa-41bb-9cb3-689e5ddb3f39.png)

**Comment by liu5201314-cyf** [comment]
大佬如果要什么补充资料或者是要我帮忙调试，可以加我微信：15816382286

**Comment by klover2** [comment]
> 

https://github.com/klover2/wechatpay-node-v3-ts/issues/34#issuecomment-1264542890

**Comment by klover2** [comment]
> 大佬如果要什么补充资料或者是要我帮忙调试，可以加我微信：15816382286

![image](https://user-images.githubusercontent.com/49548817/194683026-4ba12087-f62e-4111-a228-c1edaba11292.png)

用户名称你没有加密

**Comment by liu5201314-cyf** [comment]
好的好滴，知道了，谢谢，是我傻了
