### ISSUE TITLE
[Feature Request] 支持动态传入 appid

### ISSUE THREAD

**Issue by meteorlxy** [klover2/wechatpay-node-v3-ts#40]
## Context

微信支付商户号支持绑定多个 appid ，但是现在 sdk 只能在 constructor 中设置一个固定的 appid 。

如果需要支持多个 appid 就需要创建多个实例，然后根据 appid 动态选择对应实例来操作，不是很方便。

可以考虑将 constructor 中的值作为默认值，然后在各个方法中支持传入 appid 参数来覆盖默认值。

**Comment by klover2** [comment]
> ## Context
> 微信支付商户号支持绑定多个 appid ，但是现在 sdk 只能在 constructor 中设置一个固定的 appid 。
> 
> 如果需要支持多个 appid 就需要创建多个实例，然后根据 appid 动态选择对应实例来操作，不是很方便。
> 
> 可以考虑将 constructor 中的值作为默认值，然后在各个方法中支持传入 appid 参数来覆盖默认值。

是个好建议

**Comment by klover2** [comment]
> ## Context
> 微信支付商户号支持绑定多个 appid ，但是现在 sdk 只能在 constructor 中设置一个固定的 appid 。
> 
> 如果需要支持多个 appid 就需要创建多个实例，然后根据 appid 动态选择对应实例来操作，不是很方便。
> 
> 可以考虑将 constructor 中的值作为默认值，然后在各个方法中支持传入 appid 参数来覆盖默认值。

已经支持 新版本 [2.1.2](https://www.npmjs.com/package/wechatpay-node-v3/v/2.1.2)

**Comment by 17** [comment]
你好，这个实现有问题，虽然每个方法可以传入 appid ，但是生成 paySign 依然使用 this.appid , 会导致支付时 “支付验证签名失败” 。

https://github.com/klover2/wechatpay-node-v3-ts/blob/master/index.ts#LL530C16-L530C16

**Comment by klover2** [comment]
> 你好，这个实现有问题，虽然每个方法可以传入 appid ，但是生成 paySign 依然使用 this.appid , 会导致支付时 “支付验证签名失败” 。
> 
> https://github.com/klover2/wechatpay-node-v3-ts/blob/master/index.ts#L530

不好意思 已经修复 版本2.1.5

**Comment by klover2** [comment]
> 你好，这个实现有问题，虽然每个方法可以传入 appid ，但是生成 paySign 依然使用 this.appid , 会导致支付时 “支付验证签名失败” 。
> 
> https://github.com/klover2/wechatpay-node-v3-ts/blob/master/index.ts#L530

欢迎下次可以考虑直接提pr 我审核过后就会直接发布
