### ISSUE TITLE
[Feature Request] 升级依赖

### ISSUE THREAD

**Issue by meteorlxy** [klover2/wechatpay-node-v3-ts#41]
https://github.com/klover2/wechatpay-node-v3-ts/blob/af5185229e6d7fc7290f2f78b5f379a85cd19c7d/package.json#L14

superagent v6 已经被标记为 deprecated

**Comment by klover2** [comment]
> https://github.com/klover2/wechatpay-node-v3-ts/blob/af5185229e6d7fc7290f2f78b5f379a85cd19c7d/package.json#L14
> 
> superagent v6 已经被标记为 deprecated

已经升级到8.0.6，在测试阶段了

**Comment by klover2** [comment]
> https://github.com/klover2/wechatpay-node-v3-ts/blob/af5185229e6d7fc7290f2f78b5f379a85cd19c7d/package.json#L14
> 
> superagent v6 已经被标记为 deprecated

已发布，请升级到2.1.0

**Comment by meteorlxy** [comment]
顺便推荐一个工具 sort-package-json

**Comment by klover2** [comment]
> sort-package-json

谢谢 很好用
