### ISSUE TITLE
Hey guys, 支持可以添加合单功能吗？

### ISSUE THREAD

**Issue by medz** [klover2/wechatpay-node-v3-ts#44]
https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter5_1_4.shtml

微信支付支持合单支付，很有用的场景。

**Comment by klover2** [comment]
> https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter5_1_4.shtml
> 
> 微信支付支持合单支付，很有用的场景。

支持的，https://github.com/klover2/wechatpay-node-v3-ts/blob/master/docs/combine.md

**Comment by medz** [comment]
Thx
