### ISSUE TITLE
verifySign 的时候报错🙄

### ISSUE THREAD

**Issue by TuKun33** [klover2/wechatpay-node-v3-ts#46]
![image](https://user-images.githubusercontent.com/22310931/233058753-62cc8e45-dec8-4766-865b-fa2274bb09a5.png)

和这个有关系吗
![image](https://user-images.githubusercontent.com/22310931/233060498-e04d0a1c-a86b-4308-a90b-f44e3401ff7c.png)

代码应该是走到这了吧🤖
https://github.com/klover2/wechatpay-node-v3-ts/blob/b3668f95ac348e705e32264d0b628b7972b8cd38/index.ts#L197

**Comment by klover2** [comment]
你签名密钥是不是乱填的

**Comment by TuKun33** [comment]
> 你签名密钥是不是乱填的

我最后发现了，是sign有问题，从微信那边复制过来是34位 我把最后2位删了保留32位就ok了，奇奇怪怪😑
