### ISSUE TITLE
total 会自动除以100  1块的货 最后付了0.0.1

### ISSUE THREAD

**Issue by lizesheng0313** [klover2/wechatpay-node-v3-ts#47]

**Comment by klover2** [comment]
![image](https://user-images.githubusercontent.com/49548817/233915322-e9ca3558-3a9d-4184-9240-aeb82356f992.png)

请仔细看下微信支付金额的单位

**Comment by klover2** [comment]
> _No description provided._
![image](https://user-images.githubusercontent.com/49548817/233915865-d7e314ed-4252-4130-a96b-e6d32ca10f0c.png)

请仔细看下微信支付金额的单位

**Comment by klover2** [comment]
> _No description provided._
![image](https://user-images.githubusercontent.com/49548817/233916067-be634e9e-c413-458e-a37b-0fd66ee99356.png)

请仔细看下微信支付金额的单位
