### ISSUE TITLE
请求加上分账接口？

### ISSUE THREAD

**Issue by wxs77577** [klover2/wechatpay-node-v3-ts#48]
现在只能调用写好的方法，请问能否加上分账接口？
另外，是否可以在ts提示中开放内部的方法，便于拓展新接口。

**Comment by klover2** [comment]
> 现在只能调用写好的方法，请问能否加上分账接口？ 另外，是否可以在ts提示中开放内部的方法，便于拓展新接口。

如果存在不兼容的接口 可以使用下面的签名直接实现你想调用的接口，签名方式都是一样的
你也可以直接给我提pr 我合并之后会发布新版本的，源码都比较简单 
欢迎加入
![image](https://user-images.githubusercontent.com/49548817/234754195-294e4b6f-7c6f-4641-aa71-c30c2a5bbbfa.png)

**Comment by klover2** [comment]
> 现在只能调用写好的方法，请问能否加上分账接口？ 另外，是否可以在ts提示中开放内部的方法，便于拓展新接口。

开放的接口 文档中已经写明

![image](https://user-images.githubusercontent.com/49548817/234754473-39503c46-d10b-4382-9ee0-69fe9992691d.png)

**Comment by klover2** [comment]
> 现在只能调用写好的方法，请问能否加上分账接口？ 另外，是否可以在ts提示中开放内部的方法，便于拓展新接口。

分账接口涉及的敏感信息签名 你可以看下转账的零钱那个文档

pay.publicEncrypt('张三', Buffer.from(certificate.publicKey))

**Comment by klover2** [comment]
可以参考一下这个 由于我开通不了这个功能 测试不了，如果有问题 你就问我
https://github.com/klover2/wechatpay-node-v3-ts/blob/master/docs/profitsharing.md

**Comment by wxs77577** [comment]
> 可以参考一下这个 由于我开通不了这个功能 测试不了，如果有问题 你就问我 https://github.com/klover2/wechatpay-node-v3-ts/blob/master/docs/profitsharing.md

感谢感谢，可以用了，这效率必须赞一个！
另外，class Pay的private 属性是不是可以用protected，这样偶尔需要拓展的时候也可以在自己实现的子类里面调用（还有下面那个private sign）。

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1990059/234777896-757fa0e5-8e35-479a-a87a-c317e5ad96a4.png">

**Comment by wxs77577** [comment]
@klover2 另外，建议readme贴个打赏二维码，聊表心意 :p

**Comment by klover2** [comment]
> 

不用了 只要你们多多点赞 提优化建议就是对我最好的支持

**Comment by klover2** [comment]
> > 可以参考一下这个 由于我开通不了这个功能 测试不了，如果有问题 你就问我 https://github.com/klover2/wechatpay-node-v3-ts/blob/master/docs/profitsharing.md
> 
> 感谢感谢，可以用了，这效率必须赞一个！ 另外，class Pay的private 属性是不是可以用protected，这样偶尔需要拓展的时候也可以在自己实现的子类里面调用（还有下面那个private sign）。
> 
> <img alt="image" width="360" src="https://user-images.githubusercontent.com/1990059/234777896-757fa0e5-8e35-479a-a87a-c317e5ad96a4.png">

是个好建议 会在下个版本支持
