### ISSUE TITLE
回调 验签返回false 

### ISSUE THREAD

**Issue by ywanhzy** [klover2/wechatpay-node-v3-ts#53]
const params = {
      apiSecret: apiV3Key,
      body: bodys, 
      signature: headers["wechatpay-signature"],
      serial: headers["wechatpay-serial"],
      nonce: headers["wechatpay-nonce"],
      timestamp: headers["wechatpay-timestamp"],
    };
const ret = await pay.verifySign(params);

验签返回false

调用pay.decipher_gcm解密接口数据都返回正确

**Comment by klover2** [comment]
> const params = { apiSecret: apiV3Key, body: bodys, signature: headers["wechatpay-signature"], serial: headers["wechatpay-serial"], nonce: headers["wechatpay-nonce"], timestamp: headers["wechatpay-timestamp"], }; const ret = await pay.verifySign(params);
> 
> 验签返回false
> 
> 调用pay.decipher_gcm解密接口数据都返回正确

回调不需要验证签名， 这是主动请求微信 微信参数返回的验证

**Comment by ywanhzy** [comment]
但微信文档说---商户应当验证签名，以确认请求来自微信
加密不能保证通知请求来自微信。微信会对发送给商户的通知进行签名，并将签名值放在通知的HTTP头Wechatpay-Signature。商户应当验证签名，以确认请求来自微信，而不是其他的第三方。签名验证的算法请参考 [《微信支付API v3签名验证》](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml)。

**Comment by ywanhzy** [comment]
> > const params = { apiSecret: apiV3Key, body: bodys, signature: headers["wechatpay-signature"], serial: headers["wechatpay-serial"], nonce: headers["wechatpay-nonce"], timestamp: headers["wechatpay-timestamp"], }; const ret = await pay.verifySign(params);
> > 验签返回false
> > 调用pay.decipher_gcm解密接口数据都返回正确
> 
> 回调不需要验证签名， 这是主动请求微信 微信参数返回的验证

但微信文档说---商户应当验证签名，以确认请求来自微信
加密不能保证通知请求来自微信。微信会对发送给商户的通知进行签名，并将签名值放在通知的HTTP头Wechatpay-Signature。商户应当验证签名，以确认请求来自微信，而不是其他的第三方。签名验证的算法请参考 [《微信支付API v3签名验证》](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml)。

**Comment by klover2** [comment]
> > > const params = { apiSecret: apiV3Key, body: bodys, signature: headers["wechatpay-signature"], serial: headers["wechatpay-serial"], nonce: headers["wechatpay-nonce"], timestamp: headers["wechatpay-timestamp"], }; const ret = await pay.verifySign(params);
> > > 验签返回false
> > > 调用pay.decipher_gcm解密接口数据都返回正确
> > 
> > 
> > 回调不需要验证签名， 这是主动请求微信 微信参数返回的验证
> 
> 但微信文档说---商户应当验证签名，以确认请求来自微信 加密不能保证通知请求来自微信。微信会对发送给商户的通知进行签名，并将签名值放在通知的HTTP头Wechatpay-Signature。商户应当验证签名，以确认请求来自微信，而不是其他的第三方。签名验证的算法请参考 [《微信支付API v3签名验证》](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml)。

这是说你主动调微信支付接口 返回的参数 需要验签 ，回调不需要，回调能解签 就说明参数是正常的

**Comment by qd-xiaowang** [comment]
> > > > const params = { apiSecret: apiV3Key, body: bodys, signature: headers["wechatpay-signature"], serial: headers["wechatpay-serial"], nonce: headers["wechatpay-nonce"], timestamp: headers["wechatpay-timestamp"], }; const ret = await pay.verifySign(params);
> > > > 验签返回false
> > > > 调用pay.decipher_gcm解密接口数据都返回正确
> > > 
> > > 
> > > 回调不需要验证签名， 这是主动请求微信 微信参数返回的验证
> > 
> > 
> > 但微信文档说---商户应当验证签名，以确认请求来自微信 加密不能保证通知请求来自微信。微信会对发送给商户的通知进行签名，并将签名值放在通知的HTTP头Wechatpay-Signature。商户应当验证签名，以确认请求来自微信，而不是其他的第三方。签名验证的算法请参考 [《微信支付API v3签名验证》](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml)。
> 
> 同样的问题，请问你解决了吗？支付通知回调应该怎么处理？谢谢！

用node的crypto，这个API不支持商户平台
