### ISSUE TITLE
退款接口没有实现，要如何实现？

### ISSUE THREAD

**Issue by easyeagel** [klover2/wechatpay-node-v3-ts#56]
我看到退款接口没有实现，我效仿下单接口实现可以吗？

**Comment by klover2** [comment]
> 我看到退款接口没有实现，我效仿下单接口实现可以吗？


  https://github.com/klover2/wechatpay-node-v3-ts/blob/master/docs/transactions_h5.md
  const result = await pay.refunds(params);
