### ISSUE TITLE
hexoid is not a function

### ISSUE THREAD

**Issue by evanlong0926** [klover2/wechatpay-node-v3-ts#61]
![image](https://github.com/klover2/wechatpay-node-v3-ts/assets/52912949/9bcbd667-a8a4-4016-be22-d2a690f34103)

这是为什么？

**Comment by evanlong0926** [comment]
没事了，这是Nextjs库的问题

**Comment by guojingwen** [comment]
> 没事了，这是 `Nextjs` 框架的问题

我也遇到了。楼主怎么解决的

**Comment by guojingwen** [comment]
npm i formidable  解决了

**Comment by guojingwen** [comment]
按照 https://github.com/auth0/node-auth0/issues/798 这个

pkg文件增加配置
resolve: {
    alias: {
      "superagent": "6.0.0"
    }
  }
}
使用yarn 安装
解决了，  不知道后续会不会有什么副作用

**Comment by evanlong0926** [comment]
> 按照 [auth0/node-auth0#798](https://github.com/auth0/node-auth0/issues/798) 这个
> 
> pkg文件增加配置 resolve: { alias: { "superagent": "6.0.0" } } } 使用yarn 安装 解决了， 不知道后续会不会有什么副作用

大概率是包导出时写法的问题，包中可能使用了一个表达式。而在某些框架中对表达式不是很敏感

**Comment by hevi1991** [comment]
我从nextjs13升级到14版本后，也报了这个异常

**Comment by madrus** [comment]
Thank you @hevi1991 ! Your suggestion helped me to fix this error in my Nextjs v14 project.

**Comment by wengxiaoxiong** [comment]
两位大哥的解决办法真的可以Work，感谢！！！

**Comment by his-maj-esty** [comment]
Thanks @hevi1991
