### ISSUE TITLE
TypeError: wechatpay_node_v3_1.default is not a constructor

### ISSUE THREAD

**Issue by CooLNuanfeng** [klover2/wechatpay-node-v3-ts#66]
```js
const pay = new WxPay({
      appid: WX_APPID,
      mchid: WX_MCHID,
      publicKey: fs.readFileSync(API_CLIENT_CERT_PEM), // 公钥
      privateKey: fs.readFileSync(API_CLIENT_KEY_PEM), // 秘钥
    });

`

TypeError: wechatpay_node_v3_1.default is not a constructor

**Comment by klover2** [comment]
> ```js
> const pay = new WxPay({
>       appid: WX_APPID,
>       mchid: WX_MCHID,
>       publicKey: fs.readFileSync(API_CLIENT_CERT_PEM), // 公钥
>       privateKey: fs.readFileSync(API_CLIENT_KEY_PEM), // 秘钥
>     });
> 
> `
> 
> TypeError: wechatpay_node_v3_1.default is not a constructor
> ```

你是怎么导入模块的
