### ISSUE TITLE
能否支持unicloud使用，unicloud阿里云时需要固定出口ip，否则会出现此ip不支持调用此接口

### ISSUE THREAD

**Issue by lizhaoxrj** [klover2/wechatpay-node-v3-ts#67]
能否支持unicloud使用，unicloud阿里云时需要固定出口ip，否则会出现此ip不支持调用此接口

**Comment by lizhaoxrj** [comment]
unicloud调用https://api.mch.weixin.qq.com/v3/transfer/batches时必须使用固定ip，阿里云请求只能用官方的uniCloud.httpProxyForEip的api发送postJson请求才能使用固定ip代理，请作者能否支持下，加个配置参数可以使用 uniCloud.httpProxyForEip.postJson(url, _params, headers)进行发送请求

**Comment by lizhaoxrj** [comment]
不知道作者如何联系，如果解决能否加我微信lz18715125421告知下

**Comment by klover2** [comment]
> unicloud调用[https://api.mch.weixin.qq.com/v3/transfer/batches时必须使用固定ip，阿里云请求只能用官方的uniCloud.httpProxyForEip的api发送postJson请求才能使用固定ip代理，请作者能否支持下，加个配置参数可以使用](https://api.mch.weixin.qq.com/v3/transfer/batches%E6%97%B6%E5%BF%85%E9%A1%BB%E4%BD%BF%E7%94%A8%E5%9B%BA%E5%AE%9Aip%EF%BC%8C%E9%98%BF%E9%87%8C%E4%BA%91%E8%AF%B7%E6%B1%82%E5%8F%AA%E8%83%BD%E7%94%A8%E5%AE%98%E6%96%B9%E7%9A%84uniCloud.httpProxyForEip%E7%9A%84api%E5%8F%91%E9%80%81postJson%E8%AF%B7%E6%B1%82%E6%89%8D%E8%83%BD%E4%BD%BF%E7%94%A8%E5%9B%BA%E5%AE%9Aip%E4%BB%A3%E7%90%86%EF%BC%8C%E8%AF%B7%E4%BD%9C%E8%80%85%E8%83%BD%E5%90%A6%E6%94%AF%E6%8C%81%E4%B8%8B%EF%BC%8C%E5%8A%A0%E4%B8%AA%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8) uniCloud.httpProxyForEip.postJson(url, _params, headers)进行发送请求

正在尝试支持自定义的http请求
