### ISSUE TITLE
回调解密：Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by codesdevs** [klover2/wechatpay-node-v3-ts#70]
这个是什么原因导致的啊大佬，配置都没问题
以下是回调来的参数
resource: {
    original_type: 'transaction',
    algorithm: 'AEAD_AES_256_GCM',
    ciphertext: 'VKbMqHucBEJGzM/tj2cyt95VMT6A76evlqzev3+e7mSN/foxopMWKtSAv/5bk+bFIsHcIx3jhmz1CTS+K3CyCICBafojd4IvSYZAGxsGLrL6/ngjs20zAv7kwEoXXJXpaFyko/gRByYxHGfR8GeR0eWHUl3MqfXJdVFDie23Jli5X+APv4v7dhTyA+mO/EkMCTcVxhNt9dp9VyHLGp6RabarIM2g7BMt1pOfExsqSw8rt5WOfEnAxJa/9UyrFQdetlFhF+IuZkn41asYHCp5ABDDlixXxX6HWwuCT6C74b/qEgq8/5kSPEaBW4ntKwTlEufEmgSOjruHl8E01tuAhCuG/9UhiWFRsT9WIqfK8PnNUW9gR0ubRrsLP76UxRj7QlC+CvwH/zv0ELvUgA7qODStjonRfIqkgbrngKTy8AA+14xxsjWrg/jE7pNCESnL4HgAnhT3wJMq5ptfQfnoCmn90jTn6PUv7b0Ed7xykBv2KEk/9eaiCbhEiIgqc+jbl+kpvlHB3x9iTkc4wYTcC9ZyM3/5cd55I59lv+yt7vncR22UZjOyPc+mjxxr7rLB8SzT',
    associated_data: 'transaction',
    nonce: '9pdwAf1WzqnL'
  }

**Comment by codesdevs** [comment]
![image](https://github.com/klover2/wechatpay-node-v3-ts/assets/58060741/005a5533-443a-4b80-8a49-754c50000bda)
我一直dbug走完344行就报Unsupported state or unable to authenticate data
以下是我在343拿到的内容'{"mchid":"16****16","appid":"wx***1374","out_trade_no":"202******9194","transaction_id":"42000020***14527","trade_type":"JSAPI","trade_state":"SUCCESS","trade_state_desc":"支付成功","bank_type":"OTHERS","attach":"","success_time":"2024-02-22T16:33:20+08:00","payer":{"openid":"oQC-46******kdZpsM"},"amount":{"total":1,"payer_total":1,"currency":"CNY","payer_currency":"CNY"}}'

**Comment by 13088000432** [comment]
解决了吗？
