### ISSUE TITLE
2.1.8 升 2.2.0 报错调用支付jsapi缺少参数appid

### ISSUE THREAD

**Issue by welkinwong** [klover2/wechatpay-node-v3-ts#75]
原版本2.1.8升2.2.0后报错缺少appid

Nodejs版本：v14.21.4

生产环境 2.1.8是正常的，升到2.2.0才会报错，看了下 e8225001500060913d78c344634d065c2325cfed ，有较多代码改动，没看出是哪里引起的

**Comment by klover2** [comment]
2.2.0返回参数格式有变动，你看下返回的参数格式

**Comment by klover2** [comment]
> 原版本2.1.8升2.2.0后报错缺少appid
> 
> Nodejs版本：v14.21.4
> 
> 生产环境 2.1.8是正常的，升到2.2.0才会报错，看了下 [e822500](https://github.com/klover2/wechatpay-node-v3-ts/commit/e8225001500060913d78c344634d065c2325cfed) ，有较多代码改动，没看出是哪里引起的

2.2.0返回参数格式有变动，你看下返回的参数格式

**Comment by TuKun33** [comment]
暂时只看到这里结构变化了 [https://github.com/klover2/wechatpay-node-v3-ts/issues/79#issuecomment-2047270457](url)
